name: 'rpmbuild'
description: 'Build RPM packages'
author: 'loganbickmore'
inputs:
  spec_file:
    description: 'path to spec file'
    required: true
    default: '*.spec'
  src_archive:
    description: 'path to source archive file'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
